import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ChangeDetectorRef } from '@angular/core';
import { provideRouter, ActivatedRoute, convertToParamMap } from '@angular/router';
import { BehaviorSubject, of, Subject, throwError } from 'rxjs';
import { WisdomCardsComponent } from './wisdom-cards.component';
import { WisdomLibraryComponent } from './wisdom-library.component';
import { WisdomAdminComponent } from './wisdom-admin.component';
import { WisdomService } from '../../services/wisdom.service';
import { AuthStateService } from '../../auth/auth-state.service';
import { ToastService } from '../../services/toast.service';
const empty = { content: [], number:0, totalPages:0, first:true, last:true };
const scripture = {id:1,chapter:1,verse:1,sanskrit:'TEST SCRIPTURE PLACEHOLDER',transliteration:'TEST TRANSLITERATION',translation:'TEST TRANSLATION',sourceName:'Test fixture',sourceVersion:'test',license:'Test only',sourceUrl:'test:fixture'};
const teaching = {id:1,version:0,title:'Test editorial',scripture,simpleMeaning:'Meaning',understanding:'Explanation and example',lesson:'Takeaway',publicationDate:'2026-09-14',status:'PUBLISHED'};
const dashboard = {thought:{body:'A thoughtful word matters.'},teaching,today:'2026-09-14',timezone:'Asia/Kolkata'};
describe('Wisdom dashboard cards',()=>{
 let api: jasmine.SpyObj<WisdomService>; let fixture: ComponentFixture<WisdomCardsComponent>; let role='STUDENT';
 beforeEach(async()=>{role='STUDENT';api=jasmine.createSpyObj('WisdomService',['dashboard']);api.dashboard.and.returnValue(of(dashboard as any));await TestBed.configureTestingModule({imports:[WisdomCardsComponent],providers:[provideRouter([]),{provide:WisdomService,useValue:api},{provide:AuthStateService,useValue:{getUser:()=>({role})}}]}).compileComponents();fixture=TestBed.createComponent(WisdomCardsComponent);});
 it('renders distinct daily and weekly cards and a reading link',()=>{fixture.detectChanges();const text=fixture.nativeElement.textContent;expect(text).toContain('Thought of the Day');expect(text).toContain('Gita for Life');expect(text).toContain('A thoughtful word matters.');expect(fixture.nativeElement.querySelector('a[href="/dashboard/wisdom/gita/1"]')).toBeTruthy();});
 it('shows loading before the response',()=>{api.dashboard.and.returnValue(new Subject());fixture.detectChanges();expect(fixture.nativeElement.querySelector('[role=status]').textContent).toContain('inspiration');});
 it('handles an empty teaching library without inventing content',()=>{api.dashboard.and.returnValue(of({...dashboard,teaching:null} as any));fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('first teaching');});
 it('supports retry after failure',()=>{api.dashboard.and.returnValue(throwError(()=>new Error()));fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Try again');api.dashboard.and.returnValue(of(dashboard as any));fixture.nativeElement.querySelector('button').click();fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('A thoughtful word matters.');});
 it('shows administration only to admin roles',()=>{fixture.detectChanges();expect(fixture.nativeElement.querySelector('.manage-link')).toBeNull();role='SUB_ADMIN';fixture.debugElement.injector.get(ChangeDetectorRef).markForCheck();fixture.detectChanges();expect(fixture.nativeElement.querySelector('.manage-link')).toBeTruthy();}); // fixture.componentRef.changeDetectorRef is the host view's ref, not the component's own injected one — marking that dirty doesn't reliably re-run this OnPush component's template getters.
 it('labels retained older teaching as latest instead of this week',()=>{api.dashboard.and.returnValue(of({...dashboard,today:'2026-09-28'} as any));fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Latest teaching');});
});
describe('Wisdom library and reader',()=>{
 let api: jasmine.SpyObj<WisdomService>;let params: BehaviorSubject<any>;let fixture: ComponentFixture<WisdomLibraryComponent>;
 beforeEach(async()=>{params=new BehaviorSubject(convertToParamMap({}));api=jasmine.createSpyObj('WisdomService',['list','read']);api.list.and.returnValue(of(empty as any));api.read.and.returnValue(of(teaching as any));await TestBed.configureTestingModule({imports:[WisdomLibraryComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:{paramMap:params}},{provide:WisdomService,useValue:api}]}).compileComponents();fixture=TestBed.createComponent(WisdomLibraryComponent);});
 it('shows a meaningful empty state',()=>{fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('has not published');});
 it('renders the required reading structure with safe text',()=>{params.next(convertToParamMap({id:'1'}));fixture.detectChanges();for(const title of ['Original Sanskrit Shloka','Transliteration','Simple Meaning','Understanding & Example','Lesson for Life'])expect(fixture.nativeElement.textContent).toContain(title);expect(fixture.nativeElement.querySelector('[lang=sa]')).toBeTruthy();});
 it('cancels stale search results',()=>{const first=new Subject<any>();api.list.and.returnValue(first);fixture.detectChanges();api.list.and.returnValue(of({...empty,content:[teaching]} as any));fixture.componentInstance.q='test';fixture.componentInstance.search();first.next(empty);fixture.detectChanges();expect(fixture.componentInstance.page?.content.length).toBe(1);});
 it('clears old teaching when new route fails',()=>{params.next(convertToParamMap({id:'1'}));fixture.detectChanges();api.read.and.returnValue(throwError(()=>new Error('404')));params.next(convertToParamMap({id:'2'}));fixture.detectChanges();expect(fixture.componentInstance.teaching).toBeUndefined();expect(fixture.nativeElement.querySelector('[role=alert]')).toBeTruthy();});
});
describe('Wisdom admin workflow',()=>{
 let api: jasmine.SpyObj<WisdomService>;let toast: any;let fixture: ComponentFixture<WisdomAdminComponent>;
 beforeEach(async()=>{api=jasmine.createSpyObj('WisdomService',['status','list','saveTeaching','schedule','draft','suggestVerses']);api.status.and.returnValue(of({today:'2026-09-14',timezone:'Asia/Kolkata',upcomingScheduled:false}));api.list.and.returnValue(of(empty as any));toast={success:jasmine.createSpy(),error:jasmine.createSpy(),info:jasmine.createSpy(),confirm:jasmine.createSpy().and.resolveTo(true)};await TestBed.configureTestingModule({imports:[WisdomAdminComponent],providers:[provideRouter([]),{provide:WisdomService,useValue:api},{provide:ToastService,useValue:toast},{provide:AuthStateService,useValue:{getUser:()=>({role:'ADMIN',featureKeys:['AI_COPILOT']})}}]}).compileComponents();fixture=TestBed.createComponent(WisdomAdminComponent);fixture.detectChanges();});
 it('explains missing scripture and empty publication queue',()=>{expect(fixture.nativeElement.textContent).toContain('No verified verses');expect(fixture.nativeElement.textContent).toContain('No upcoming teaching');expect(fixture.componentInstance.teachingForm.invalid).toBeTrue();});
 it('requires explicit confirmation before publishing',async()=>{toast.confirm.and.resolveTo(false);await fixture.componentInstance.schedule(teaching as any);expect(api.schedule).not.toHaveBeenCalled();});
 it('schedules with an explicit time when the admin sets one',async()=>{const c=fixture.componentInstance;c.dateForm.setValue({date:'2026-09-21',time:'07:00'});api.schedule.and.returnValue(of(teaching as any));await c.schedule(teaching as any);expect(api.schedule).toHaveBeenCalledWith(teaching as any,'2026-09-21','07:00');});
 it('defaults to no explicit time (school-local midnight) when the admin leaves it blank',async()=>{const c=fixture.componentInstance;c.dateForm.setValue({date:'2026-09-21',time:''});api.schedule.and.returnValue(of(teaching as any));await c.schedule(teaching as any);expect(api.schedule).toHaveBeenCalledWith(teaching as any,'2026-09-21',null);});
 it('saving a draft never schedules it',()=>{const c=fixture.componentInstance;c.teachingForm.setValue({verseId:1,title:'Title',simpleMeaning:'Meaning',understanding:'Example',lesson:'Lesson',version:0});api.saveTeaching.and.returnValue(of(teaching as any));c.saveTeaching();expect(api.saveTeaching).toHaveBeenCalled();expect(api.schedule).not.toHaveBeenCalled();});
 it('AI changes editorial inputs only and does not persist',async()=>{const c=fixture.componentInstance;c.selectVerse(scripture as any);c.themeForm.setValue({theme:'Focus'});api.draft.and.returnValue(of({simpleMeaning:'Draft meaning',understanding:'Draft example',lesson:'Draft lesson'}));await c.draft();expect(c.teachingForm.controls.verseId.value).toBe(1);expect(c.selectedScripture?.sanskrit).toBe('TEST SCRIPTURE PLACEHOLDER');expect(api.saveTeaching).not.toHaveBeenCalled();expect(api.schedule).not.toHaveBeenCalled();});
 it('retains edits when saving fails',()=>{const c=fixture.componentInstance;c.teachingForm.setValue({verseId:1,title:'Keep this',simpleMeaning:'Meaning',understanding:'Example',lesson:'Lesson',version:0});api.saveTeaching.and.returnValue(throwError(()=>new Error()));c.saveTeaching();expect(c.teachingForm.controls.title.value).toBe('Keep this');expect(c.busy).toBeFalse();});
 it('suggesting verses populates ranked results and using one selects it',()=>{const c=fixture.componentInstance;c.suggestForm.setValue({theme:'anger and self-control'});api.suggestVerses.and.returnValue(of([{scripture,rationale:'Speaks to self-control.'}] as any));c.suggestVerses();expect(c.suggestions?.length).toBe(1);c.useSuggestion(c.suggestions![0]);expect(c.selectedScripture).toEqual(scripture as any);expect(c.teachingForm.controls.verseId.value).toBe(1);});
 it('shows an empty state when no verses match the suggested theme',()=>{const c=fixture.componentInstance;c.suggestForm.setValue({theme:'a very specific unmatched theme'});api.suggestVerses.and.returnValue(of([]));c.suggestVerses();fixture.detectChanges();expect(c.suggestions?.length).toBe(0);expect(fixture.nativeElement.textContent).toContain('No verified verses matched that theme yet');});
});
